version: '3.5'

services:
  node:
    build: .
    command: bash -c "cd nodebb-plugin-quickstart/ && npm link && cd .. && npm link nodebb-plugin-quickstart && node ./nodebb build && node ./nodebb start"
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "127.0.0.1:4567:4567"
    volumes: 
      - node_data:/usr/src/app

  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: gesloadmin
      POSTGRES_DB: nodebb
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgres/data
    volumes:
      - postgres:/var/lib/postgres/data/
  
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment: 
      PGADMIN_DEFAULT_EMAIL: jasa@kero.si
      PGADMIN_DEFAULT_PASSWORD: gesloadmin
      PGADMIN_LISTEN_PORT: 80
    ports: 
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    links: 
      - "db:pgsql-server"

volumes:
  postgres:
  node_data:
  pgadmin_data: