version: '3.5'

services:
  node:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    #expose:
      #- 4567 # use a reverse proxy like Traefik
    ports:
      - "127.0.0.1:4567:4567"
    volumes: 
      - ./:/node

  db:
    image: mongo:bionic
    restart: unless-stopped
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: gesloadmin
    volumes:
      - mongo:/data/db

volumes:
  mongo:
